# Generated by Django 5.0.6 on 2024-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bike_count', models.IntegerField(default=0)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('steps', models.CharField(choices=[('first', 'الاولى'), ('second', 'الثانية'), ('third', 'الثالثة'), ('completed', 'مكتمل ✅')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_price', models.FloatField()),
                ('available_motorcycles', models.PositiveIntegerField(default=0)),
                ('soldout_motorcycles', models.PositiveIntegerField(default=0)),
                ('total_rental_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bike_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
