# Generated by Django 5.0.6 on 2024-06-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_motorcycle_remove_user_bike_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'العميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='motorcycle',
            options={'verbose_name': 'الدراجة النارية', 'verbose_name_plural': 'الدراجات النارية'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='client',
            name='steps',
            field=models.CharField(choices=[('first', 'الاولى'), ('second', 'الثانية'), ('completed', 'مكتمل ✅')], max_length=20),
        ),
    ]
