# Generated by Django 5.0.6 on 2024-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_options_alter_motorcycle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_text', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'الاعدادات',
                'verbose_name_plural': 'الاعدادات',
            },
        ),
    ]
